title: HPC Office Hours
description: Getting onto the supercomputer, from the terminal and from Tapis
remote_theme: pages-themes/cayman@v0.2.0
plugins:
  - jekyll-remote-theme

exclude:
  - README.md
  - slides/
